---
- include: _preliminary_check.yml

- include: _remove_previous.yml
  when: haproxy_bin.stat.exists

- include: _create.yml

- include: _download.yml

- include: _make.yml

- include: _install.yml

- include: _config.yml

- include: _initd.yml

- include: _haproxyctl.yml
  when: haproxy_haproxyctl

- name: start haproxy
  service: >
    name=haproxy
    enabled=yes
    state=started
