---
# PRELIMINARY

- include: _haproxyctl_statuscheck_up.yml
  when: rails_app_run == 'first' and rails_app_haproxyctl and rails_app_type == 'server'

- include: _haproxyctl_detach.yml
  when: rails_app_haproxyctl and rails_app_type == 'server'

- include: _rvm_passenger_standalone_stop.yml
  when: rails_app_server == 'passenger_standalone' and rails_app_rvm and rails_app_type == 'server'

- include: _port_stop_listening.yml
  when: rails_app_type == 'server'

# RELEASE

- include: _release_set_new_release_path.yml
  when: rails_app_run == 'first'

# DEPLOY

- include: _deploy_current_app.yml

- include: _deploy_binstubs.yml
  when: rails_app_type == 'server'

- include: _rvm_passenger_standalone_start.yml
  when: rails_app_server == 'passenger_standalone' and rails_app_rvm and rails_app_type == 'server'

- include: _port_start_listening.yml
  when: rails_app_type == 'server'

- include: _haproxyctl_attach.yml
  when: rails_app_haproxyctl and rails_app_type == 'server'

- include: _ping_app.yml
  when: rails_app_type == 'server'

- include: _haproxyctl_healthcheck_up.yml
  when: rails_app_type == 'server'

- include: _deploy_complete.yml
  when: rails_app_run == 'last'
