# ---
# app_name: hyperion

# app_user: vagrant

# app_instances:
#   - id: titanium
#     port: 4000
#     host: 127.0.0.1
#     protocol: tcp

#   - id: carbon
#     port: 4001
#     host: 127.0.0.1
#     protocol: tcp

# app_healthcheck_uri: ok.html

# db_user: "{{ mysql_application_username }}"
# db_pass: "{{ mysql_application_password }}"

# app_platform: production


---
app_name: hyperion
app_user: vagrant

app_healthcheck_uri: hc/ok.html

app_instances:
  - id: titanium
    port: 4000
    host: 127.0.0.1
    protocol: tcp
    run: first
    type: server

  - id: carbon
    port: 4001
    host: 127.0.0.1
    protocol: tcp
    run: last
    type: server

app_server_instances:
  - "{{ app_instances[0] }}"
  - "{{ app_instances[1] }}"
