---

rails_app_name: "{{ app_name }}"
rails_app_user: "{{ app_user }}"
rails_app_http_check_uri: "{{ app_healthcheck_uri }}"

rails_app_host: 127.0.0.1
rails_app_platform: "{{ app_user }}"
rails_app_production_ready: true
rails_app_purge_all: false

rails_app_git_repo: https://github.com/mikechau/haproxy-passenger-standalone-rolling-upgrades.git
rails_app_git_branch: master

rails_app_all_instances: "{{ app_instances }}"

rails_app_rvm: true

rails_app_haproxy: true

rails_app_db_username: "{{ db_user }}"
rails_app_db_password: "{{ db_pass }}"

rails_app_env_config:
  APPLICATION_NAME: "{{ app_name }}"
