---

rails_app_name: "{{ app_name }}"
rails_app_user: "{{ app_user }}"
rails_app_http_check_uri: "{{ app_healthcheck_uri }}"

rails_app_purge_all: false

rails_app_server_instances: "{{ app_server_instances }}"

rails_app_instances: "{{ app_instances }}"

rails_app_rvm: true
rails_app_haproxyctl: true

rails_app_db_adapter: mysql2
rails_app_db_host: localhost
rails_app_db_port: 3306
rails_app_db_pool: 25
rails_app_db_use_socket: true
rails_app_db_socket_path: /var/lib/mysql/mysql.sock
rails_app_db_username: "{{ mysql_application_username }}"
rails_app_db_password: "{{ mysql_application_password }}"

rails_app_git_repo: https://github.com/mikechau/haproxy-passenger-standalone-rolling-upgrades.git
rails_app_git_branch: master

rails_app_env_config:
  APPLICATION_ID: "{{ rails_app_id }}"
  APPLICATION_NAME: "{{ app_name }}"

rails_app_environment:
  RAILS_ENV: production

# rails_app_platform: production